config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :notes
  get 'welcome/index'
  
  authenticated :user do
    root 'notes#index', as: "authenticated_root"
  end
  
  root 'welcome#index'
  
end

app/models/note.rb
class Note < ActiveRecord::Base
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
    before_action :find_note, only: [:show, :edit, :update, :destroy]
    
    def index
        @notes = Note.where(user_id: current_user)
    end
    
    def show
    end
    
    def new
        @note = current_user.notes.build
    end
    
    def create
        @note = current_user.notes.build(note_params)
        if @note.save
            redirect_to @note
        else
            render :new
        end
    end
    
    def edit
        
    end
    
    def update
        if @note.update(note_params)
            redirect_to @note
        else
            render :edit
        end
    end
    
    def destroy
        @note.destroy
        redirect_to notes_path
    end
    
    private
    
    def find_note
        @note = Note.find(params[:id])
    end
    
    def note_params
        params.require(:note).permit(:title, :content)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title Notebook
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  %link{ :rel => "stylesheet", :href => "//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"}/
  = csrf_meta_tags
  
%body

  %header
    .header_inner
      = link_to image_tag('logo.svg'), root_path, id: "logo"
      %nav
        - if user_signed_in?
          = link_to "new_note", new_note_path
          = link_to "sign_out", destroy_user_session_path, method: :delete
        - else
          = link_to "login", new_user_session_path
        
  - flash.each do |name, msg|
    = content_tag :div, msg, class: "notice"
    
  = yield

app/views/notes/_form.html.haml
= simple_form_for @note do |f|
    = f.input :title
    = f.input :content
    = f.button :submit

app/views/notes/edit.html.haml
%h1 Edit your note
= render "form"

app/views/notes/index.html.haml
.wrapper_with_padding
	#notes.clearfix
		- unless @notes.blank?
			- @notes.each do |note|
				%a{ href: (url_for [note])}
					.note
						%p.title= note.title
						%p.date= time_ago_in_words(note.created_at)
		- else
			%h2 Add a Note
			%p It appears you haven't created any notes yet... Lets fix that. Why don't you go ahead and create a new note.
			%button= link_to "New Note", new_note_path

app/views/notes/new.html.haml
.wrapper_with_padding
	%h1 Add A Note

	= render 'form'

app/views/notes/show.html.haml
.wrapper_with_padding
	#note_show
		%h1.title= @note.title
		%p= simple_format(@note.content)

		.buttons
			= link_to "Edit", edit_note_path(@note), class: "button"
			= link_to "Delete", note_path(@note), method: :delete, data: { confirm: "Are you sure?" }, class: "button"

app/views/welcome/index.html.haml
#banner
    .banner_content
        %h1 Notebook
        %p Your online notebook, never forget your ideas again
        %button= link_to "Sign up", new_user_registration_path

#testimonial
    .wrapper
        %p.quote "A good notebook application"
        %p.name - Vickris
        
        
#callouts
    .callout_inner
        .wrapper
            .callout
                %i.fa.fa-pencil
                %h2 Notes
                %p
                    Chia paleo Wes Anderson umami whatever cronut Pitchfork normcore sartorial.
                    Trust fund readymade semiotics, fashion axe four loko pickled messenger bag.
                    Thundercats scenester street art, mumblecore direct trade YOLO ethical tattooed raw denim. Literally paleo bespoke c
            .callout
                %i.fa.fa-rocket
                %h2 Shooot
                %p
                    Chia paleo Wes Anderson umami whatever cronut Pitchfork normcore sartorial.
                    Trust fund readymade semiotics, fashion axe four loko pickled messenger bag.
                    Thundercats scenester street art, mumblecore direct trade YOLO ethical tattooed raw denim. Literally paleo bespoke c
            .callout
                %i.fa.fa-send
                %h2 Yass
                %p
                    Chia paleo Wes Anderson umami whatever cronut Pitchfork normcore sartorial.
                    Trust fund readymade semiotics, fashion axe four loko pickled messenger bag.
                    Thundercats scenester street art, mumblecore direct trade YOLO ethical tattooed raw denim. Literally paleo bespoke c
                    
#bottom_cta
    .wrapper
        %h2 For Realz!
        %p I want you to sign up... If you don’t. I will find you!
        %button= link_to "Click Meee!!!", new_user_registration_path

%footer
    %p &copy; Vickris